### ISSUE TITLE
AssertionError in fairsquare/src/vol.py, line 420

### ISSUE THREAD

**Issue by bishwamittra** [sedrews/fairsquare#1]
Hi, 
I am trying the running example with the following command (from 'src' directory) 

`python fairProve.py -f ex.fr -mi -mf` 

and I am getting an assertion error. I have also used -z flag to use z3 for quantifier elimination and got the same error. Here I attach the log from my terminal output.
[log.txt](https://github.com/sedrews/fairsquare/files/5093900/log.txt)

Best, 
Bishwa

**Comment by sedrews** [comment]
Hi Bishwa,

I am not able to reproduce this error. Can you let me know what version of z3 you're using (e.g. run `python -c 'import z3; print(z3.get_version_string())'`)? I'm using a fairly old version: 4.7.0

Best,
Sam

**Comment by bishwamittra** [comment]
Hi Sam, 

My z3 version was the latest. I have downgraded z3 to 4.7.1 and now the error does not appear. 

It would be convenient if you mention the working version z3  in the readme. 

Thanks again, 
Bishwa
